# -*- coding: utf-8 -*-
"""bigdata-themelangfreq

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tduoXwDEWVacYt0bk_ufuBfqm30EKfi2

# Install Necessary Packages
"""

from pyspark.sql import SparkSession
from pyspark.sql.functions import split, col, countDistinct, sum as _sum, desc, row_number

"""# Init Spark"""

# Initialize Spark
spark = SparkSession.builder.appName("Theme-Frequency-By-Language").getOrCreate()

# 1. Load and parse the data (replace with your actual file)
df = spark.read.text("s3://sg.edu.sit.inf2006.aaronlam/ThemeLanguageAnalysisFolder/mr_preprocessing/output/part-r-00000")

# 2. Parse into columns (Language, Theme, Count)
parsed_df = df.withColumn("temp", split(col("value"), " - ")) \
              .withColumn("language", col("temp")[0]) \
              .withColumn("theme_count", split(col("temp")[1], "\t")) \
              .withColumn("theme", col("theme_count")[0]) \
              .withColumn("count", col("theme_count")[1].cast("integer")) \
              .drop("value", "temp", "theme_count")

# Register the parsed DataFrame as a temporary view for easier querying
parsed_df.createOrReplaceTempView("theme_language_counts")

"""# Analysis

## 1. Top 3 languages of all themes
"""

top_languages_df = spark.sql("""
    SELECT
        language,
        SUM(count) AS total_count
    FROM theme_language_counts
    GROUP BY language
    ORDER BY total_count DESC
    LIMIT 3
""")

top_languages = [row.language for row in top_languages_df.collect()]

"""## 2. Themes with the largest % of the top languages

"""

theme_language_percentage_df = spark.sql("""
    WITH ThemeTotalCounts AS (
        SELECT
            theme,
            SUM(count) AS theme_total
        FROM theme_language_counts
        GROUP BY theme
    ),
    ThemeLanguageCounts AS (
        SELECT
            theme,
            language,
            SUM(count) AS language_count
        FROM theme_language_counts
        WHERE language IN ('{}', '{}', '{}') -- Insert top 3 languages
        GROUP BY theme, language
    )
    SELECT
        tlc.theme,
        tlc.language,
        tlc.language_count,
        ttc.theme_total,
        (tlc.language_count / ttc.theme_total) * 100 AS percentage
    FROM ThemeLanguageCounts tlc
    JOIN ThemeTotalCounts ttc ON tlc.theme = ttc.theme
""".format(top_languages[0], top_languages[1], top_languages[2]))

theme_top_3_percentage_df = theme_language_percentage_df.groupBy("theme") \
    .agg(_sum("percentage").alias("top_3_percentage")) \
    .orderBy(desc("top_3_percentage"))

top_3_themes_df = theme_top_3_percentage_df.limit(3)
top_3_themes = [row.theme for row in top_3_themes_df.collect()]

"""## Theme with the MOST & LEAST number of Languages"""

theme_language_count_df = parsed_df.groupBy("theme") \
    .agg(countDistinct("language").alias("num_languages"))

top_theme_df = theme_language_count_df.orderBy(desc("num_languages"))
top_theme_languages = top_theme_df.first()
max_language_count = top_theme_languages.num_languages
themes_with_max = top_theme_df.filter(col("num_languages") == max_language_count).collect()

least_theme_df = theme_language_count_df.orderBy("num_languages")
least_theme_languages = least_theme_df.first()
min_language_count = least_theme_languages.num_languages
themes_with_min = least_theme_df.filter(col("num_languages") == min_language_count).collect()

"""## Final Output Analysis"""

print("Top 3 Languages Across All Themes:")
print(top_languages)

print("\nTop 3 themes with the highest percentage of the Top 3 languages:")
for theme in top_3_themes:
    print(f"\nTheme: {theme}")
    theme_language_percentages = theme_language_percentage_df.filter(col("theme") == theme).orderBy(desc("percentage")).collect()
    for row in theme_language_percentages:
        print(f"  Language: {row.language}, Percentage: {row.percentage:.2f}%")

print("\nTheme(s) with the Most Number of Languages:")
for row in themes_with_max:
    print(f"Theme: {row.theme}, with {row.num_languages} Languages!")

print("\nTheme(s) with the Least Number of Languages:")
for row in themes_with_min:
    print(f"Theme: {row.theme}, with {row.num_languages} Languages.")


# # Output path in S3
output_path = "s3://sg.edu.sit.inf2006.aaronlam/ThemeLanguageAnalysisFolder/spark_analysis/output/"

# Save DataFrame as CSV
# Write DataFrames into separate subdirectories
parsed_df.coalesce(1).write.mode("overwrite").option("header", "true").csv(output_path)

# Stop Spark
spark.stop()

